version: 2
updates:
  # Rust (Cargo) - Parser
  - package-ecosystem: "cargo"
    directory: "/parser"
    schedule:
      interval: "weekly"

  # Rust (Cargo) - Summarizer
  - package-ecosystem: "cargo"
    directory: "/summarizer"
    schedule:
      interval: "weekly"

  # Go (Go modules)
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly" 