name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build Rust parser
        run: |
          cd parser && cargo build --release
      - name: Build Rust summarizer
        run: |
          cd summarizer && cargo build --release
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Build Go CLI
        run: |
          cd cmd && go build -o codesleuth.exe
      - name: Test pipeline
        run: |
          # Test that the pipeline works end-to-end
          echo '{"program_name":"TEST","source_file":"test.cbl"}' | ./summarizer/target/release/summarizer 